### ISSUE TITLE
RSS sortering

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/duk_op#365]
RSS på IF's side bliver sorteret efter hvornår eventet er oprettet og ikke efter hvornår eventet sker. Det gør funktionaliteten til meget mindre brugervenlig. Kan det ændres?

Vibeke skriver:

> Det er superfedt, at Ronan knokler på, men det største problem ved feedet er faktisk dets karakter af feed - hvor man sorterer efter hvornår eventen er lagt ind og ikke hvornår eventen finder sted. En brugervenlig kalender sorteres jo netop efter, hvornår noget finder sted og ikke efter hvornår et opslag er oprettet. 
> 
> Så hvis Ronan på en eller anden måde kan få den kringlet ville det være fantastisk. Men jeg tror ærlig talt ikke, at det er teknisk muligt med et feed.
> 
> Vi bruger Drupal 8s date-modul til at sortere de kalenderopslag, som bliver lagt direkte ind på Internationalt Forums nye hjemmeside, hvis den information kan være en hjælp.

**Comment by ronan-mch** [comment]
hi, I can understand the use case, but my understanding of RSS is that
items should be ordered by published date. This makes the most sense when
you consider the primary use case is news, blogs etc. This is of course a
symptom of using RSS for something where another format would be more
appropriate. No finger pointing here, the ecosystem support for calendar
formats is the problem, so we must do the best we can with what's
available. What I suggest is to add an optional URL parameter e.g.
locations/8.rss?sort_by=calendar which will sort as per calendar date
rather than date published. I should be able to get it done over the
weekend.

2016-07-07 16:37 GMT+02:00 tadoh <notifications@github.com>:

**Comment by ronan-mch** [comment]
sorry, I looked at this again now and it looks like sorting **is** happening according to date occurring rather than date published. You can see this on [Ungdomshuset's feed](https://www.dukop.dk/locations/10.rss?locale=da) for example. If things are being re-sorted on the client end, it's the feed module that is re-sorting according to the `pubDate` element, which in all honestly is quite correct behaviour. You might want to investigate whether this behaviour can be overridden in the module's settings.

Tagging @biveke.

**Comment by biveke** [comment]
I see what you mean. Now I have to think....hmmm

**Comment by biveke** [comment]
But I can also see, that if you mix feeds from two different users (IF have two different user-accounts on Duk Op, one for Verdensakademiet and one for Internationalt Forum) they are not sorted by date in the feed-stream, so to speak. I tried with Verdensakademiet and Ungdomshuset, and Verdensakademiets feed item about Gaza is first (12. august), next comes Ungdomhusets 'Anarkistisk Studie etc.' (12. juli) and then next comes Ungdomshuset 'Thaiboksning...' (14. juli). So they will probably be mixed up after all no matter what I do, because of the two different accounts. And I looks as if the Feeds module from Drupal 8 is still in a development state and functions as a traditional module for fetching feeds as news items, not as some kind of calendar items. 

I guess we're making everything very difficult for ourselves in Internationalt Forum...

**Comment by ronan-mch** [comment]
Hej Biveke, kan du tjekke igen med `sort_by=calendar` på URL-en og se om det hjælper? F.eks. https://www.dukop.dk/locations/14.rss?locale=da&sort_by=calendar

**Comment by biveke** [comment]
Jeg prøver Ronan.

**Comment by biveke** [comment]
Jeg får en fejlmeddelelse, når jeg prøver at erstatte 
https://www.dukop.dk/locations/14.rss?locale=da&sort_by=calendar med
fx https://www.dukop.dk/users/182.rss?locale=da

Jeg vil ikke poste hele fejlmeddelelsen herinde, men den starter med: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_feed_link_title' at row 1: INSERT INTO...

**Comment by biveke** [comment]
Jeg prøvede med vegetarforeningens bruger https://www.dukop.dk/locations/102.rss?locale=da&sort_by=calendar, som vistnok er dem, der har lagt flest kalenderopslag ind - og jo, det virker med rækkefølgen. Men jeg kan jo ikke vide, hvilken rækkefølge de har lagt deres opslag ind i. Altså om den rækkefølge der afspejler sig er den rækkefølge, som de har lagt opslagene ind i - eller der reelt sorteres på dato...så den nærmeste dato kommer øverst. 

Men jeg tror i det hele taget lige at jeg skal have talt lige så grundigt med Nicola om det her, som jeg har talt med Marie, inden du knokler videre med det her. For jeg er ikke helt sikker på, at Nicola har set, hvor stort problemet i virkeligheden er. Ligegyldigt hvor smukt dit arbejde er, så er jeg seriøst bange for at samspillet mellem kalenderopslagene fra rundt om i landet og af vidt forskellig karakter aldrig bliver særligt brugervenligt på vores site - og det handler om nogle andre ting end det, som du med dit supergode arbejde kan gøre noget ved. Der er for mange forskellige kanaler, for mange forskellige redaktionelle linjer og for mange forskellige former for funktionalitet i spil til, at det kan blive harmonisk og fedt og let at gå til for slutbrugerne.

Så indtil videre tak for hjælpen. Det er fedt, men det er ikke sikkert at det nogensinde bliver fedt på IFs hjemmeside, desværre.

**Comment by benjaoming** [comment]
Hey!

Det er ærgerligt, at det ikke lige kunne lade sig gøre. Vi arbejder gerne videre med RSS-delen, men ift. at understøtte de nævnte dele her, så kan vi 1) Lave feeds pr. sted, 2) sortere efter publikationsdata, 3) sortere efter begivenhedsdato og 4) sortere efter andet, der måtte blive efterspurgt.

Så jeg lukke den her, men så kan der jo altid være en grund til at snakke om muligheden igen.
